version: "3.8"

volumes:
  db:
services:
  node:
    image: node:18.12.1-alpine3.16
    ports:
      - "8102:5000"
    volumes:
      - ./:/usr/src
    working_dir: /usr/src
    command: npm start
  mysql:
    image: mariadb:10.9.4
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=shop
    volumes:
      - db:/var/lib/mysql
