version: "3.8"

services:
  node:
    image: node:$NODE_VERSION
    ports:
      - "8102:5000"
    volumes:
      - ./:/usr/src
    working_dir: /usr/src
    command: sh -c "npm install && npm run build && npm start"
